config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end


  root to: "top#index"
  resources :posts, only: :index
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<div class="top-header">
 <div class="top-header__containers">

   <div class="top-header__containers__top">
     <div class="top-header__containers__top__icon">
      メルカリロゴ
     </div>
     <div class="top-header__containers__top__search">
      何かお探しですか？
     </div>
   </div>

   <div class="top-header__containers__bottom">
    <div class="top-header__containers__bottom__search">
       <div class="top-header__containers__bottom__search__category">
        カテゴリーから探す
      </div>
      <div class="top-header__containers__bottom__search__brand">
        ブランドから探す
      </div>
    </div>
    <div class="top-header__containers__bottom__user">
    <% if user_signed_in? %>
     <div class="top-header__containers__bottom__user__signup">
      <%= link_to 'マイページ', posts_path %>
     </div>
    </div>

    <% else %>
    <div class="top-header__containers__bottom__user">
     <div class="top-header__containers__bottom__user__signup">
      <%= link_to '新規会員登録', posts_path %>
     </div>
     <div class="top-header__containers__bottom__user__login">
      <%= link_to 'ログイン', new_user_session_path %>
     </div>
    </div>
    <% end %>
  </div>


 </div>
</div>


<div class="top-contents">
  <div class="top-contents__sell">
   <%= link_to '出品', new_product_path %>

  </div>

  <div class="top-contents__photo">
   写真
  </div>

  <div class="top-contents__category">
   人気のカテゴリー
   <%= link_to '商品一覧ページへ', products_path %>

  </div>

  <div class="top-contents__brand">
   人気のブランド
  </div>

</div>


<div class="top-footer">
  <div class="top-footer__container">
    <ul class="top-footer__container__title">
    <li>メルカリについて</li>
    <li>ヘルプ＆ガイド</li>
    <li>プライバシーと利用規約</li>
    <li>国</li>
    </ul>
  </div>
</div>